### ISSUE TITLE
Hackintool crashes in Ventura 13.6

### ISSUE THREAD

**Issue by yanisalbert** [benbaker76/Hackintool#205]
Hi,
I updated Hackintool to the latest but it crashes at the opening.

This is the report.

Thanks

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Hackintool [10275]
Path:                  /Applications/Hackintool.app/Contents/MacOS/Hackintool
Identifier:            com.Headsoft.Hackintool
Version:               3.9.9 (0399)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-22 07:03:16.1781 +0200
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Anonymous UUID:        D128A4F7-FE82-9CA6-8B40-6CC72C20CAD5

Sleep/Wake UUID:       4D925DBC-6E3E-4BD8-8213-C29B25FAADD6

Time Awake Since Boot: 5100 seconds
Time Since Wake:       3243 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
Referenced from: <BD7C2270-5B9C-3751-B6BB-A52970540F19> /Applications/Hackintool.app/Contents/MacOS/Hackintool
Reason: tried: '/Applications/Hackintool.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <5A4580EE-A890-34FE-89D1-B9A730E89621> '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <5A4580EE-A890-34FE-89D1-B9A730E89621> '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/Hackintool.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle'
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff812f24c52 __abort_with_payload + 10
1   dyld                          	    0x7ff812f3efd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff812f3f009 abort_with_payload + 9
3   dyld                          	    0x7ff812ec38f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff812ec0b71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff812ebf3bd start + 1805

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7ba440498  rdx: 0x00007ff7ba440900
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7ba4404e0  rsp: 0x00007ff7ba440498
   r8: 0x00007ff7ba440500   r9: 0x0000000000000000  r10: 0x0000000000000077  r11: 0x0000000000000246
  r12: 0x0000000000000077  r13: 0x00007ff7ba440900  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff812f24c52  rfl: 0x0000000000000246  cr2: 0x0000000105c74000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x105abe000 -        0x105b55fff com.Headsoft.Hackintool (3.9.9) <bd7c2270-5b9c-3751-b6bb-a52970540f19> /Applications/Hackintool.app/Contents/MacOS/Hackintool
    0x7ff812eb9000 -     0x7ff812f515ef dyld (*) <3df96f32-b9c9-3566-a6b7-4daebc6d6563> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=172.5M resident=0K(0%) swapped_out_or_unallocated=172.5M(100%)
Writable regions: Total=8452K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8452K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                             507K        2 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       171.3M        2 
__TEXT                            1220K        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            237.2M       15 

-----------
Full Report
-----------

{"app_name":"Hackintool","timestamp":"2023-09-22 07:03:16.00 +0200","app_version":"3.9.9","slice_uuid":"bd7c2270-5b9c-3751-b6bb-a52970540f19","build_version":"0399","platform":1,"bundleID":"com.Headsoft.Hackintool","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6 (22G120)","roots_installed":0,"name":"Hackintool","incident_id":"0C750AD0-3EC4-4AD0-8E70-E845D96F29B3"}
{
  "uptime" : 5100,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac20,2",
  "coalitionID" : 5327,
  "osVersion" : {
    "train" : "macOS 13.6",
    "build" : "22G120",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-22 07:03:16.1781 +0200",
  "incident" : "0C750AD0-3EC4-4AD0-8E70-E845D96F29B3",
  "pid" : 10275,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-22 07:03:16.1669 +0200",
  "procStartAbsTime" : 5124073530229,
  "procExitAbsTime" : 5124084627091,
  "procName" : "Hackintool",
  "procPath" : "\/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool",
  "bundleInfo" : {"CFBundleShortVersionString":"3.9.9","CFBundleVersion":"0399","CFBundleIdentifier":"com.Headsoft.Hackintool"},
  "storeInfo" : {"deviceIdentifierForVendor":"59FF98BD-0B46-5C55-82F5-A535BABF88AA","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.Headsoft.Hackintool",
  "crashReporterKey" : "D128A4F7-FE82-9CA6-8B40-6CC72C20CAD5",
  "codeSigningID" : "com.Headsoft.Hackintool",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 3243,
  "sleepWakeUUID" : "4D925DBC-6E3E-4BD8-8213-C29B25FAADD6",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Sparkle.framework\/Versions\/B\/Sparkle","Referenced from: <BD7C2270-5B9C-3751-B6BB-A52970540F19> \/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool","Reason: tried: '\/Applications\/Hackintool.app\/Contents\/MacOS\/..\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' (code signature in <5A4580EE-A890-34FE-89D1-B9A730E89621> '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' (code signature in <5A4580EE-A890-34FE-89D1-B9A730E89621> '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/Applications\/Hackintool.app\/Contents\/MacOS\/..\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle'"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":121646,"threadState":{"r13":{"value":140701958670592},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701958669568},"cr2":{"value":4391911424},"rdx":{"value":140701958670592},"r10":{"value":119},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703446486098,"matchesCrashFrame":1},"rbp":{"value":140701958669536},"rsp":{"value":140701958669464},"r12":{"value":119},"rcx":{"value":140701958669464},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441426,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4390117376,
    "CFBundleShortVersionString" : "3.9.9",
    "CFBundleIdentifier" : "com.Headsoft.Hackintool",
    "size" : 622592,
    "uuid" : "bd7c2270-5b9c-3751-b6bb-a52970540f19",
    "path" : "\/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool",
    "name" : "Hackintool",
    "CFBundleVersion" : "0399"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703446044672,
    "size" : 624112,
    "uuid" : "3df96f32-b9c9-3566-a6b7-4daebc6d6563",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703445422080,
  "size" : 21474836480,
  "uuid" : "2434d7b8-6144-3aef-92fd-a483c33f40d2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=172.5M resident=0K(0%) swapped_out_or_unallocated=172.5M(100%)\nWritable regions: Total=8452K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8452K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                             507K        2 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       171.3M        2 \n__TEXT                            1220K        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            237.2M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "5c05aaaac6d852d4ca3c219efffac72e8d507046",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000019
    },
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    }
  ]
}
}

Model: iMac20,2, BootROM 2005.0.0.0.0, 10 processors, 10-Core Intel Core i9, 3,6 GHz, 64 GB, SMC 
Graphics: AMD Radeon RX 580, AMD Radeon RX 580, PCIe, 4 GB
Display: Mi Monitor, 3440 x 1440 (UWQHD - Ultra-Wide Quad HD), Main, MirrorOff, Online
Display: Beyond TV, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), MirrorOff, Online
Memory Module: BANK 1/ChannelA-DIMM1, 32 GB, DDR4, 3200 MHz, 029E, CMK64GX4M2E3200C16
Memory Module: BANK 3/ChannelB-DIMM1, 32 GB, DDR4, 3200 MHz, 029E, CMK64GX4M2E3200C16
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Intel I225V 2.5 Gbit, Ethernet, en3
Network Service: Wi-Fi, AirPort, en1
PCI Card: Intel UHD Graphics 630, VGA compatible controller, Internal@0,2,0
PCI Card: Realtek 1220-VB, Audio device, Internal@0,31,3
PCI Card: Intel I219V11 PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,31,6
PCI Card: AMD Radeon RX 580, Display Controller, Slot-1@0,1,0/0,0
PCI Card: BCM4360 802.11ac Wireless Network Adapter, Network controller, Internal@0,28,2/0,0
PCI Card: Intel JHL7540 Titan Ridge Thunderbolt 3 NHI, Thunderbolt-Controller, Thunderbolt
PCI Card: Intel JHL7540 Titan Ridge USB 3.1, USB eXtensible Host-Controller, Thunderbolt
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
Serial ATA Device: Samsung SSD 850 PRO 512GB, 512,11 GB
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: 4-Port USB 3.1 Hub
USB Device: UAC-2
USB Device: ITE Device
USB Device: USB2.0 Hub
USB Device: NZXT USB Device
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
USB Device: Keyboard Hub
USB Device: USB-PS/2 Optical Mouse
USB Device: iLok
USB Device: Apple Keyboard
USB Device: 4-Port USB 2.1 Hub
USB Device: hub_device
USB Device: Poly Studio P5 webcam
Thunderbolt Bus:

**Comment by iferret** [comment]
+1

**Comment by originalmagneto** [comment]
Need to BUMP this? Glad I'm not the only one here...

**Comment by zinohome** [comment]
Me too, crashed in Ventura 13.6

**Comment by OnSale1980** [comment]
me too. can't open it at all.

**Comment by telepati** [comment]
Yes, I tested also, only v3.9.7 is opening.

**Comment by jpschwengber** [comment]
Sim, eu testei também, apenas a v3.9.7 está abrindo.

**Comment by benbaker76** [comment]
I just released a new version with an updated Sparkle framework. Please try it and let me know if it works

**Comment by victorBuzdugan** [comment]
For me it's still not working.
_macOS 13.5.2 (22G91)
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle_
It works with v3.9.7

**Comment by sicole1804** [comment]
> I just released a new version with an updated Sparkle framework. Please try it and let me know if it works

v4 also doesn't work, app doesn't launch. macOS Ventura 13.5 13.6 and Sonoma RC2

**Comment by Forlorn-Hope** [comment]
Also having the same issue on 13.4


-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Hackintool [17211]
Path:                  /Applications/Hackintool.app/Contents/MacOS/Hackintool
Identifier:            com.Headsoft.Hackintool
Version:               4.0.0 (0400)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-22 15:54:19.4699 -0400
OS Version:            macOS 13.4 (22F66)
Report Version:        12
Anonymous UUID:        67F844E4-9263-242B-1ED1-CB17502472DF

Sleep/Wake UUID:       961AC036-1A8F-4707-8C81-24E0B74712FC

Time Awake Since Boot: 2100000 seconds
Time Since Wake:       1534 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
Referenced from: <37AF161D-B154-3CBA-9CC6-00D046BCF85B> /Applications/Hackintool.app/Contents/MacOS/Hackintool
Reason: tried: '/Applications/Hackintool.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <FB04743D-4F86-31FC-8C50-FF45B447156B> '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <FB04743D-4F86-31FC-8C50-FF45B447156B> '/Applications/Hackintool.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/Hackintool.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle'
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff81c2a3c42 __abort_with_payload + 10
1   dyld                          	    0x7ff81c2bdfd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff81c2be009 abort_with_payload + 9
3   dyld                          	    0x7ff81c2428f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff81c23fb71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff81c23e3bd start + 1805


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b2263498  rdx: 0x00007ff7b2263900
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b22634e0  rsp: 0x00007ff7b2263498
   r8: 0x00007ff7b2263500   r9: 0x0000000000000000  r10: 0x0000000000000077  r11: 0x0000000000000246
  r12: 0x0000000000000077  r13: 0x00007ff7b2263900  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff81c2a3c42  rfl: 0x0000000000000246  cr2: 0x000000010de51000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x10dc9b000 -        0x10dd32fff com.Headsoft.Hackintool (4.0.0) <37af161d-b154-3cba-9cc6-00d046bcf85b> /Applications/Hackintool.app/Contents/MacOS/Hackintool
    0x7ff81c238000 -     0x7ff81c2d05cf dyld (*) <9e98a840-a3ac-31c1-ab97-829af9bd6864> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=172.4M resident=0K(0%) swapped_out_or_unallocated=172.4M(100%)
Writable regions: Total=8452K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8452K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                             507K        2 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       171.2M        3 
__TEXT                            1220K        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            237.2M       16 



-----------
Full Report
-----------

{"app_name":"Hackintool","timestamp":"2023-09-22 15:54:19.00 -0400","app_version":"4.0.0","slice_uuid":"37af161d-b154-3cba-9cc6-00d046bcf85b","build_version":"0400","platform":1,"bundleID":"com.Headsoft.Hackintool","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"Hackintool","incident_id":"65B4CC2D-53E0-4275-ACF2-22EF11F2C302"}
{
  "uptime" : 2100000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac19,1",
  "coalitionID" : 149707,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-22 15:54:19.4699 -0400",
  "incident" : "65B4CC2D-53E0-4275-ACF2-22EF11F2C302",
  "pid" : 17211,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-22 15:54:19.4622 -0400",
  "procStartAbsTime" : 2152501097464533,
  "procExitAbsTime" : 2152501104886393,
  "procName" : "Hackintool",
  "procPath" : "\/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.0","CFBundleVersion":"0400","CFBundleIdentifier":"com.Headsoft.Hackintool"},
  "storeInfo" : {"deviceIdentifierForVendor":"A5992799-7E34-51CF-A2D3-A5628F3C3702","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.Headsoft.Hackintool",
  "crashReporterKey" : "67F844E4-9263-242B-1ED1-CB17502472DF",
  "codeSigningID" : "com.Headsoft.Hackintool",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1534,
  "sleepWakeUUID" : "961AC036-1A8F-4707-8C81-24E0B74712FC",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Sparkle.framework\/Versions\/B\/Sparkle","Referenced from: <37AF161D-B154-3CBA-9CC6-00D046BCF85B> \/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool","Reason: tried: '\/Applications\/Hackintool.app\/Contents\/MacOS\/..\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' (code signature in <FB04743D-4F86-31FC-8C50-FF45B447156B> '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' (code signature in <FB04743D-4F86-31FC-8C50-FF45B447156B> '\/Applications\/Hackintool.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/Applications\/Hackintool.app\/Contents\/MacOS\/..\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle'"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":24494509,"threadState":{"r13":{"value":140701822499072},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701822498048},"cr2":{"value":4528082944},"rdx":{"value":140701822499072},"r10":{"value":119},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703601146946,"matchesCrashFrame":1},"rbp":{"value":140701822498016},"rsp":{"value":140701822497944},"r12":{"value":119},"rcx":{"value":140701822497944},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441410,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4526288896,
    "CFBundleShortVersionString" : "4.0.0",
    "CFBundleIdentifier" : "com.Headsoft.Hackintool",
    "size" : 622592,
    "uuid" : "37af161d-b154-3cba-9cc6-00d046bcf85b",
    "path" : "\/Applications\/Hackintool.app\/Contents\/MacOS\/Hackintool",
    "name" : "Hackintool",
    "CFBundleVersion" : "0400"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703600705536,
    "size" : 624080,
    "uuid" : "9e98a840-a3ac-31c1-ab97-829af9bd6864",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703600082944,
  "size" : 21474836480,
  "uuid" : "867bf49e-1375-3009-9693-a1621961928a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=172.4M resident=0K(0%) swapped_out_or_unallocated=172.4M(100%)\nWritable regions: Total=8452K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8452K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                             507K        2 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       171.2M        3 \n__TEXT                            1220K        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            237.2M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "3a703cdb928ee17c7f2813a6b0e4cbe43f918f00",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    },
    {
      "rolloutId" : "62699e1ec1ff2978b47f6c3b",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "631f72d1de559130376df1fb"
      },
      "deploymentId" : 240000023
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac19,1, BootROM 1968.100.16.0.1, 8 processors, 8-Core Intel Core i9, 3.6 GHz, 32 GB, SMC 2.46f12
Graphics: AMD Radeon RX 590, AMD Radeon RX 590, PCIe, 8 GB
Display: DELL P2314H, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 3000 MHz, 029E, CMD32GX4M4C3000C15
Memory Module: BANK 1/ChannelA-DIMM1, 8 GB, DDR4, 3000 MHz, 029E, CMD32GX4M4C3000C15
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 3000 MHz, 029E, CMD32GX4M4C3000C15
Memory Module: BANK 3/ChannelB-DIMM1, 8 GB, DDR4, 3000 MHz, 029E, CMD32GX4M4C3000C15
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 860 EVO 1TB, 1 TB
USB Device: USB31Bus
USB Device: 4-Port USB 3.0 Hub
USB Device: USB2.0 Hub
USB Device: hub_device
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: 4-Port USB 2.0 Hub
USB Device: G502 HERO Gaming Mouse
Thunderbolt Bus:

**Comment by benbaker76** [comment]
Please try 4.0.1

**Comment by victorBuzdugan** [comment]
> Please try 4.0.1

Sorry but it's still not working.
The same error.

**Comment by benbaker76** [comment]
Okay please try 4.0.2

**Comment by sicole1804** [comment]
> Okay please try 4.0.2

4.0.2 working fine now, thank you for your efforts!

**Comment by benbaker76** [comment]
I sometimes forget that when I merge a pull request I need to check if the certs have changed.

Anyways thanks for testing!

**Comment by Forlorn-Hope** [comment]
4.0.2 worked for me. 

 

Thank you!

 

 

From: benbaker76 ***@***.***>
Reply-To: benbaker76/Hackintool ***@***.***>
Date: Friday, September 22, 2023 at 4:11 PM
To: benbaker76/Hackintool ***@***.***>
Cc: Forlorn-Hope ***@***.***>, Comment ***@***.***>
Subject: Re: [benbaker76/Hackintool] Hackintool crashes in Ventura 13.6 (Issue #205)

 

Okay please try 4.0.2

**Comment by benbaker76** [comment]
PS Please don't forget to star this project! I'm trying to reach 4096 stars!

**Comment by victorBuzdugan** [comment]
Changes in 4.02 did the job. It's working now.
Thank you for a very useful app and for the fast responses.

**Comment by OnSale1980** [comment]
Thanks. it's working with latest version 4.0.2

**Comment by jpschwengber** [comment]
4.0.2 funcionou para mim, obrigado!

**Comment by yanisalbert** [comment]
It works now. Thanks
